# server
server:
  port: 60012
#  spring
spring:
  application:
    name: eureka-server
#  security:
#    user:
#      password: 123456
#      name: admin
# eureka
eureka:
  instance:
    hostname: eureka2
  server:
    enable-self-preservation: true
  client:
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    # false表示不向注册中心注册自己。
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka0:60010/eureka, http://eureka1:60011/eureka



