## server1
#server1:
#  host: 192.168.223.137
#server2:
#  host: 192.168.223.138
#server3:
#  host: 192.168.223.139
#
#
## server
server:
  port: 8012
#  spring
spring:
  application:
    name: eureka-server

# eureka
eureka:
  instance:
    hostname: eureka2
  server:
    enable-self-preservation: false
  client:
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    # false表示不向注册中心注册自己。
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka0:8010/eureka, http://eureka1:8011/eureka



