server:
  port: 8030

spring:
  application:
    name: order # 注册到eureka server的服务名
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka0:8010/eureka/, http://eureka1:8010/eureka/, http://eureka2:8010/eureka/ # eureka server的地址


my-config: my-config